### PR TITLE
Fluent api

### PR DESCRIPTION
**Pull request by Toilal**
This implements #6, #9 and #10

I'll make other features based on this branch (Constructor testing, and maybe others ...)

### CODE REVIEW

**Comment by hazendaz** [comment]
Nice work!  I'll get a chance to review this better tonight.  Once I approve are you wanting a release or possibly have other things coming?


Sent by Outlook for Android





On Mon, Jul 27, 2015 at 8:15 AM -0700, "Rémi Alvergnat" <notifications@github.com> wrote:
This implements #6, #9 and #10

I'll make other features based on this branch (Constructor testing, and maybe others ...)
You can view, comment on, or merge this pull request online at:

  https://github.com/hazendaz/javabean-tester/pull/11

-- Commit Summary --

  * Add IDEA Project files to .gitignore
  * Fix invalid LoadType switch
  * Add fluent API and refactor

-- File Changes --

    M .gitignore (5)
    M src/main/java/com/codebox/bean/JavaBeanTester.java (391)
    A src/main/java/com/codebox/bean/JavaBeanTesterBuilder.java (56)
    A src/main/java/com/codebox/bean/JavaBeanTesterWorker.java (365)
    A src/main/java/com/codebox/bean/ValueBuilder.java (207)
    M src/test/java/com/codebox/bean/JavaBeanTesterTest.java (5)

-- Patch Links --

https://github.com/hazendaz/javabean-tester/pull/11.patch
https://github.com/hazendaz/javabean-tester/pull/11.diff

---
Reply to this email directly or view it on GitHub:
https://github.com/hazendaz/javabean-tester/pull/11

**Comment by Toilal** [comment]
Release would be great, even if I think i'll be able to provide a PR this week for #8 and #7

**Comment by Toilal** [comment]
@hazendaz I'll fix formatting by using Eclipse and the format.xml file.

Also, i'll create a new branch based on this one to start working on the next features i've planned.

**Comment by hazendaz** [comment]
Cool thanks.


Sent by Outlook for Android





On Tue, Jul 28, 2015 at 1:29 AM -0700, "Rémi Alvergnat" <notifications@github.com> wrote:
@hazendaz I'll fix formatting by using Eclipse and the format.xml file.

Also, i'll create a new branch based on this one to start working on the next features i've planned.

---

**Comment by hazendaz** [comment]
Very nice work!

**Pull request merged**
