### PR TITLE
Add a check in the equalsHashCode test to only rerun getterSetter tes…

### PR DESCRIPTION
**Pull request by goblinsan**
…ts on classes with setters.  Allows for @Value annotated classes to run the check successfully.

### CODE REVIEW

**Comment by hazendaz** [comment]
@goblinsan I'm going to bring this in through a separate merge keeping your commits as you have them with a few adjustments on top.  Mostly styling issues (javadocs / imports with .*).  I'm guessing you use Intellij and this is pretty configured for Eclipse and/or my preferences :)  Anyway nice work and good job on cleaning up that props duplication.  Thanks for the additional support.  Let me know if you will have anything else coming in or if this is it.  If this is all you need for now, I'll push a release out after I hear back from you.

**Comment by hazendaz** [comment]
merged and now on master

**Comment by goblinsan** [comment]
@hazendaz Thanks, that should be all I need.  I did notice that the intellij's organize imports was a bit aggressive, but figured i'd let you make the call on that.  Thanks for getting this merged!

**Comment by hazendaz** [comment]
@goblinsan No problem!  Thanks for this.  I have released this to sonatype.  It will start showing up in central in next two hours.

**Pull request merged**
